# Ignore engine warnings for pnpm-based packages
packageExtensions:
  "@whop/api@*":
    peerDependencies:
      "@auth/core": "^0.40.0"
  "@whop/react@*":
    peerDependencies:
      react: "^19.0.0"
      react-dom: "^19.0.0"
  "@whop/iframe@*":
    peerDependencies:
      react: "^19.0.0"
      react-dom: "^19.0.0"

# Suppress engine field warnings
logFilters:
  - code: YN0002
    level: discard
  - code: YN0060
    level: discard